### ISSUE TITLE
Broken sourcemap warning

### ISSUE THREAD

**Issue by equinusocio** [nyanyani/rollup-plugin-svg-sprite-loader#7]
I have this warning on my rollup configuration, can't figure out what's wrong because sourcemap are set to `true`

```sh
(!) Broken sourcemap
(!) Broken sourcemap https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "rollup-plugin-svg-sprite-loader") should generate accompanying sourcemaps
```

## Rollup config

```js
import { nodeResolve } from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import typescript from '@rollup/plugin-typescript'
import { terser } from 'rollup-plugin-terser'
import external from 'rollup-plugin-peer-deps-external'
import postcss from 'rollup-plugin-postcss'
import svg from 'rollup-plugin-svg-sprite-loader'
import cleaner from 'rollup-plugin-cleaner'

export default [
  {
    input: 'index.ts',
    output: [
      {
        file: "dist/index.js",
        format: "cjs",
        sourcemap: true
      }
    ],
    external: ['react', 'react-dom', 'framer-motion'],
    plugins: [
      external(),
      cleaner({
        targets: [
          './dist/'
        ]
      }),
      typescript({ tsconfig: './tsconfig.json' }),
      nodeResolve(),
      commonjs(),
      svg({
        extract: true,
        publicPath: './'
      }),
      postcss({
        modules: true,
        extract: true,
        minimize: true
      }),
      terser()
    ]
  }
]

```

**Comment by nyanyani** [comment]
I am gonna figure it out, it might take a while cause my network is broken xD .

**Comment by nyanyani** [comment]
~~I did some reaserch last night and found out this problem may be related to rollup/babel ([rollup/rollup#2592](https://github.com/rollup/rollup/issues/2592)).~~

Wonder if this missing `map` property in [transform hook](https://rollupjs.org/guide/en/#transform) causes this issue, keep trying ...

---

### Update

One config opiton solved this problem and here are a tip I want to share: 

[If it doesn't make sense to generate a sourcemap](https://rollupjs.org/guide/en/#source-code-transformations), `return {  code: transformedCode,  map: { mappings: '' }};` every time. And in this scenario, svg file content is invalid for sourcemap.

~~Woking on `index.d.ts` now and a patch will be applied soon 😄 .~~

Returning `map: {mappings: ''}` in `renderChunk` hook will generate empty sourcemap, maybe manually generate mappings with [source-map](https://www.npmjs.com/search?q=source%2Dmap) is a solution. 🤒
